version: 2
jobs:
 build:
   machine: true
   steps:
    - checkout

    # login 
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    # build the application image
    - run: docker build -t jcuffney/node-ci-image:latest .

    # deploy the image
    - run: docker push jcuffney/node-ci-image:latest