version: 2
jobs:

 build:
   machine: true
   steps:
    - checkout

    - run: export TAG="0.1.$CIRCLE_BUILD_NUM"

    # login
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    # build the application image
    - run: docker build -t jcuffney/node-ci-image:$TAG .

    # deploy the image
    - run: docker push jcuffney/node-ci-image:$TAG
