version: 2

defaults: &defaults
  docker: 
    - image: ubuntu:latest
  working_directory: ~/repo

jobs:

  docker_install:
    <<: *defaults
    steps:
      - run: apt-get update
      - run: apt-get install -y curl
      - run: curl -sSL https://get.docker.com/ 41 | sh

  docker_login:
    <<: *defaults
    steps:
      - run: apt-get update
      - run: apt-get install -y curl
      - run: curl -sSL https://get.docker.com/ 41 | sh

  build: 
    <<: *defaults
    steps:
      - checkout
      - run: make build

  push:
    <<: *defaults
    steps:
      - checkout
      - run: make push
          
workflows:
  version: 2
  build:
    jobs:
      - docker_install
      - docker_login:
        requires:
          - docker_install
      - build:
        requires:
          - docker_install
      - push:
        requires:
          - docker_login
          - build
